import type { ComponentType } from "preact";

type ToolImport = () => Promise<{ default: ComponentType }>;

export const toolRegistry: Record<string, ToolImport> = {
  "investment-sim": () => import("./investment-sim/InvestmentSim.tsx"),
  "compound-interest": () => import("./compound-interest/CompoundInterest.tsx"),
  "supply-demand": () => import("./supply-demand/SupplyDemand.tsx"),
  "amortization-race": () => import("./amortization-race/AmortizationRace.tsx"),
  "evolution-trust": () => import("./evolution-trust/EvolutionTrust.tsx"),
  "segregation-sim": () => import("./segregation-sim/SegregationSim.tsx"),
  "voting-systems": () => import("./voting-systems/VotingSystems.tsx"),
  "cloth-sim": () => import("./cloth-sim/ClothSim.tsx"),
  "em-field": () => import("./em-field/EmField.tsx"),
  "optics-bench": () => import("./optics-bench/OpticsBench.tsx"),
  "entropy-demon": () => import("./entropy-demon/EntropyDemon.tsx"),
  "pendulum-lab": () => import("./pendulum-lab/PendulumLab.tsx"),
  "bayesian-inference": () => import("./bayesian-inference/BayesianInference.tsx"),
  "calculus-viz": () => import("./calculus-viz/CalculusViz.tsx"),
  "complex-numbers": () => import("./complex-numbers/ComplexNumbers.tsx"),
  "gradient-boosting": () => import("./gradient-boosting/GradientBoosting.tsx"),
  "dim-reduction": () => import("./dim-reduction/DimReduction.tsx"),
  "loss-landscape": () => import("./loss-landscape/LossLandscape.tsx"),
  "tokenizer-compare": () => import("./tokenizer-compare/TokenizerCompare.tsx"),
  "process-scheduler": () => import("./process-scheduler/ProcessScheduler.tsx"),
  "dns-resolver": () => import("./dns-resolver/DnsResolver.tsx"),
  "tcp-viz": () => import("./tcp-viz/TcpViz.tsx"),
  "page-replacement": () => import("./page-replacement/PageReplacement.tsx"),
  "compiler-pipeline": () => import("./compiler-pipeline/CompilerPipeline.tsx"),
  "flow-field": () => import("./flow-field/FlowField.tsx"),
  "tessellation": () => import("./tessellation/Tessellation.tsx"),
  "lissajous": () => import("./lissajous/Lissajous.tsx"),
  "spirograph": () => import("./spirograph/Spirograph.tsx"),
  "search-engine": () => import("./search-engine/SearchEngine.tsx"),
  "git-viz": () => import("./git-viz/GitViz.tsx"),
  "loopy": () => import("./loopy/Loopy.tsx"),
};
